version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cliquealomx-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cliquealomx-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cliquealomx-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/cliquealomx?authSource=admin
      - PORT=3001
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - cliquealomx-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cliquealomx-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - cliquealomx-network

volumes:
  mongodb_data:

networks:
  cliquealomx-network:
    driver: bridge
