[variables]
NODE_VERSION = "20"
NIXPACKS_NODE_VERSION = "20"

[node]
version = "20"

[phases.install]
cmds = ["cd backend && npm ci --include=dev"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm run start:prod"