[node]
version = "20"

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "cd backend && npm install",
  "cd backend && npm run build",
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "npm run start"