[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "cd backend && npm install",
  "cd backend && npm run build",
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "npm run start"